id: ID030906A
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W3CN1823
  ocr_info:
    timestamp: 08/17/23T19:39:24
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-28 23:09:26.560528+00:00
last_modified: 2024-02-28 23:09:26.560535+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1823
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1823
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སོག་ཡུལ་དུ་སྤར་བའི་མདོ་རྒྱུད་ཁག་ཅིག
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9486767892182615
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN1828:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1828
      total_pages: 594
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1828.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9563151199033141
  I3CN1829:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1829
      total_pages: 208
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN1829.txt
    statistics:
      ocr_word_median_confidence_index: 0.98
      ocr_word_mean_confidence_index: 0.9020520378663341
  I3CN1830:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1830
      total_pages: 1134
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN1830.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9387601195602614
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
